// Curated list of common French words organized by length
// Each word has been verified for correct length

const WORDS_5: string[] = [
	'ABORD', 'ACIER', 'ADIEU', 'AGILE', 'AIDER', 'AIMER', 'ALBUM', 'ANCRE',
	'ARBRE', 'ASTRE', 'AUSSI', 'AUTRE', 'AVANT', 'AVOIR', 'BARBE', 'BAGUE',
	'BILAN', 'BLANC', 'BLOND', 'BOIRE', 'BOITE', 'BOMBE', 'BOTTE', 'BRAVE',
	'BRISE', 'CABLE', 'CALME', 'CANAL', 'CARTE', 'CAUSE', 'CHAIR', 'CHAMP',
	'CHANT', 'CLAIR', 'COEUR', 'CONTE', 'CORPS', 'COUDE', 'COUPE', 'COURT',
	'CRABE', 'CRIME', 'CRISE', 'CROIX', 'CUIRE', 'CYCLE', 'DENSE', 'DIGNE',
	'DIVAN', 'DOIGT', 'DOUCE', 'DROIT', 'DROLE', 'DUVET', 'ECLAT', 'ENCRE',
	'ENVIE', 'ETAGE', 'ETUDE', 'EXACT', 'FAIRE', 'FARCE', 'FAUTE', 'FERME',
	'FETER', 'FIBRE', 'FIGUE', 'FINAL', 'FIXER', 'FLANC', 'FLEUR', 'FORCE',
	'FORME', 'FOSSE', 'FOULE', 'FRAIS', 'FRANC', 'FRONT', 'FRUIT', 'GALET',
	'GARDE', 'GELER', 'GLOBE', 'GOMME', 'GRAIN', 'GRAND', 'GRAVE', 'GREVE',
	'GUIDE', 'HERBE', 'HEURE', 'HIVER', 'HUILE', 'IMAGE', 'ISSUE', 'JAMBE',
	'JAUNE', 'JETER', 'JEUNE', 'JOUER', 'JURER', 'LAMPE', 'LARGE', 'LEVER',
	'LIBRE', 'LIEGE', 'LIGNE', 'LINGE', 'LITRE', 'LIVRE', 'LOUER', 'LOURD',
	'LOYAL', 'LUEUR', 'LUNDI', 'MARGE', 'MARIN', 'MASSE', 'MELON', 'MERCI',
	'MINCE', 'MONDE', 'MONTE', 'MOULE', 'NAPPE', 'NEIGE', 'NOBLE', 'NOTER',
	'NUAGE', 'OBJET', 'OFFRE', 'OLIVE', 'OMBRE', 'ONCLE', 'ORAGE', 'ORGUE',
	'PAIRE', 'PANNE', 'PAUSE', 'PECHE', 'PEINE', 'PENTE', 'PERLE', 'PIANO',
	'PIECE', 'PISTE', 'PLACE', 'PLAGE', 'PLEIN', 'PLUIE', 'POEME', 'POIDS',
	'POINT', 'POMME', 'PORTE', 'POUCE', 'PRISE', 'PROIE', 'PRUNE', 'QUART',
	'REINE', 'RICHE', 'RIDER', 'RONDE', 'ROUGE', 'ROUTE', 'RUSER', 'SABLE',
	'SALON', 'SAUCE', 'SCENE', 'SIGNE', 'SOBRE', 'SOMME', 'SONGE', 'STADE',
	'STYLO', 'SUCRE', 'SUITE', 'TABLE', 'TACHE', 'TARTE', 'TASSE', 'TEMPO',
	'TERRE', 'TIGRE', 'TITRE', 'TOILE', 'TONNE', 'TORSE', 'TRACE', 'TRAIN',
	'TRAIT', 'TRONC', 'USINE', 'VAGUE', 'VEINE', 'VENIR', 'VERRE', 'VIDER',
	'VILLE', 'VITRE', 'VIVRE', 'VOILE', 'VOLER'
];

const WORDS_6: string[] = [
	'ACCORD', 'AMANDE', 'AUCUNE', 'BATEAU', 'BESOIN', 'BEURRE', 'BIJOUX',
	'BILLET', 'BOUCHE', 'BOUGIE', 'BRAISE', 'BRETON', 'BROCHE', 'BRONZE',
	'CABANE', 'CASQUE', 'CHAISE', 'CHANCE', 'CHANGE', 'CHEVAL', 'CINEMA',
	'CIRQUE', 'CLOCHE', 'COFFRE', 'COMBAT', 'COMMUN', 'COPAIN', 'COURSE',
	'CROIRE', 'CUIVRE', 'DANGER', 'DESSIN', 'DETAIL', 'DEVOIR', 'DISQUE',
	'DOUBLE', 'ECOUTE', 'EFFORT', 'ENIGME', 'ENTIER', 'EPOQUE', 'ESPRIT',
	'ETOILE', 'FACADE', 'FIGURE', 'FLACON', 'FLAMME', 'FLECHE', 'FLEUVE',
	'FORGER', 'FOURMI', 'FRACAS', 'FRANGE', 'GALERE', 'GATEAU', 'GOUTTE',
	'GRADIN', 'GUERRE', 'HASARD', 'HUMAIN', 'JARDIN', 'JOUEUR', 'JUMENT',
	'LANGUE', 'LAVAGE', 'LEVIER', 'LONGUE', 'LOUCHE', 'MAISON', 'MARBRE',
	'MARCHE', 'MAUDIT', 'MENACE', 'MESURE', 'METIER', 'MINUTE', 'MIROIR',
	'MOITIE', 'MOTEUR', 'MOUCHE', 'MOUTON', 'MUSEAU', 'NATURE', 'NOMBRE',
	'ORANGE', 'PALAIS', 'PAPIER', 'PARDON', 'PARLER', 'PENSEE', 'PHRASE',
	'PIERRE', 'PIGEON', 'PILOTE', 'PLAINE', 'PLANTE', 'PLAQUE', 'POESIE',
	'POISON', 'POLICE', 'POMPER', 'PORTER', 'POTION', 'PRENOM', 'PRINCE',
	'PRISON', 'RAISON', 'RAPPEL', 'RASOIR', 'REGIME', 'RELIER', 'REMISE',
	'REPERE', 'REQUIN', 'RETOUR', 'RIDEAU', 'RIVAGE', 'SAISON', 'SAVANT',
	'SECRET', 'SENTIR', 'SIGNAL', 'SIMPLE', 'SIRENE', 'SOLEIL', 'SOURCE',
	'STATUE', 'SUCCES', 'TEMPLE', 'TENDRE', 'TIMBRE', 'TORCHE', 'TREMPE',
	'TROUPE', 'VALEUR', 'VALISE', 'VAPEUR', 'VENDRE', 'VERGER', 'VISAGE',
	'VISITE', 'VOYAGE'
];

const WORDS_7: string[] = [
	'ABANDON', 'ABEILLE', 'ABSURDE', 'ACCUEIL', 'ADAPTER', 'ADMIRER', 'AGENCER',
	'ALARMER', 'BALANCE', 'BARRAGE', 'BERCEAU', 'BIZARRE', 'BLOQUER', 'BONHEUR',
	'BOUCHER', 'BOUQUET', 'BRIGADE', 'BRILLER', 'BRISURE', 'CABINET', 'CALIBRE',
	'CAPABLE', 'CAPTEUR', 'CELLULE', 'CERTAIN', 'CHALEUR', 'CHAMBRE', 'CHARGER',
	'CHATEAU', 'CHEMISE', 'CLOTURE', 'COLLIER', 'COLONNE', 'COMMUNE', 'COMPLET',
	'CONSEIL', 'CONTACT', 'CONTENU', 'COSTUME', 'COURAGE', 'COUSSIN', 'CULTURE',
	'DEFENSE', 'DEMANDE', 'DERNIER', 'DESSERT', 'DISPARU', 'DOSSIER', 'ECLIPSE',
	'ECRASER', 'EMBLEME', 'EMOTION', 'EMPLOYE', 'ENERGIE', 'ENVOYER', 'EPISODE',
	'ESSENCE', 'EVASION', 'EXEMPLE', 'EXERCER', 'EXPLOIT', 'EXTREME', 'FATIGUE',
	'FERMIER', 'FICTION', 'FOSSILE', 'FOURNIR', 'GALERIE', 'GLACIER', 'GLOBALE',
	'GRILLER', 'GRIMPER', 'HABITAT', 'HONNEUR', 'HORIZON', 'HOSTILE', 'INSTANT',
	'JANVIER', 'JOURNEE', 'JUSTICE', 'LANGAGE', 'LECTURE', 'LENTEUR', 'LOGIQUE',
	'LUMIERE', 'MACHINE', 'MAGASIN', 'MALADIE', 'MALHEUR', 'MANCHOT', 'MARIAGE',
	'MATIERE', 'MEMOIRE', 'MENTEUR', 'MESSAGE', 'MIRACLE', 'MODESTE', 'MONTAGE',
	'MYSTERE', 'NOTABLE', 'OBTENIR', 'OPINION', 'OUVRAGE', 'PALMIER', 'PANACHE',
	'PARTAGE', 'PASSAGE', 'PATIENT', 'PENSION', 'PINCEAU', 'PLAFOND', 'PLANETE',
	'PLONGER', 'POISSON', 'PORTION', 'POUVOIR', 'PREFACE', 'PREMIER', 'PRESENT',
	'PRESSER', 'PREVOIR', 'PROFOND', 'PROUVER', 'QUALITE', 'RACONTE', 'REALITE',
	'RECOLTE', 'REFAIRE', 'REMPLIR', 'REPLIER', 'REPONSE', 'RESERVE', 'RESPECT',
	'REUNION', 'ROUTINE', 'RUPTURE', 'SAGESSE', 'SECONDE', 'SEMAINE', 'SERVICE',
	'SILENCE', 'SOMMEIL', 'SOUTIEN', 'SURFACE', 'TABLEAU', 'TERRAIN', 'TONNEAU',
	'TOURNER', 'TRAVAIL', 'TRIBUNE', 'TROUVER', 'VAINCRE', 'VEILLER', 'VILLAGE',
	'VIOLENT', 'VITESSE', 'VOLTIGE', 'VOYAGER'
];

const WORDS_8: string[] = [
	'ACCEPTER', 'ACCOMPLI', 'AFFIRMER', 'ALPHABET', 'ANNONCER', 'APPAREIL',
	'ARRIVAGE', 'AUDIENCE', 'AVANTAGE', 'AVENTURE', 'BAPTISER', 'BATIMENT',
	'BONHOMME', 'BOUILLON', 'BOUTIQUE', 'BRAVOURE', 'CAMPAGNE', 'CANDIDAT',
	'CARAVANE', 'CHAMPION', 'CHANTEUR', 'CHAPELLE', 'CHOCOLAT', 'COLLECTE',
	'COMMANDE', 'COMMERCE', 'COMMUNAL', 'COMPLETE', 'COMPREND', 'CONQUETE',
	'CONTENIR', 'CONTINUE', 'CONTROLE', 'CREATURE', 'CRITIQUE', 'DECISION',
	'DEMANDER', 'DEPASSER', 'DESIGNER', 'DIALOGUE', 'DIMANCHE', 'DISTANCE',
	'DOCUMENT', 'ECHAPPER', 'ECLAIRER', 'ECONOMIE', 'ELOQUENT', 'EMBRASSE',
	'ENCEINTE', 'ENSEMBLE', 'ESCALIER', 'ETONNANT', 'EVIDENCE', 'EXAMINER',
	'FABRIQUE', 'FONTAINE', 'FRACTION', 'FRINGALE', 'FROMAGES', 'GLACIALE',
	'HABITUEL', 'HARMONIE', 'HERITAGE', 'HISTOIRE', 'HUMIDITE', 'ILLUSION',
	'IMAGINER', 'IMMEUBLE', 'IMPERIAL', 'INCIDENT', 'INCLINER', 'INQUIETE',
	'INTIMITE', 'INVENTER', 'JALOUSIE', 'JEUNESSE', 'JOYEUSES', 'LANTERNE',
	'LIMONADE', 'LOGEMENT', 'LONGUEUR', 'MECHANTE', 'MEDECINE', 'MEMOIRES',
	'MENSONGE', 'MODIFIER', 'MONARQUE', 'MONOPOLE', 'MONTAGNE', 'MOUTARDE',
	'NATURELS', 'NOBLESSE', 'NOMBREUX', 'NOTABLES', 'NOURRICE', 'NOUVELLE',
	'OBJECTIF', 'OBSTACLE', 'OFFICIEL', 'ORCHIDEE', 'ORGANISE', 'ORIGINAL',
	'PACIFIER', 'PAIEMENT', 'PARCOURS', 'PASSAGER', 'PENDULES', 'PLANCHER',
	'PLASTRON', 'POIGNARD', 'PORTRAIT', 'POSSIBLE', 'PRATIQUE', 'PROBLEME',
	'PRODUIRE', 'PROFITER', 'PROPOSER', 'PROTEGER', 'PROVERBE', 'PROVINCE',
	'PRUDENCE', 'PUNITION', 'QUESTION', 'RACONTER', 'REALISER', 'REGARDER',
	'REMONTER', 'REMPLACE', 'REPARTIR', 'REPONDRE', 'REPROCHE', 'RESIDENT',
	'RESPECTE', 'RICHESSE', 'RUBRIQUE', 'SCENARIO', 'SECURITE', 'SENSIBLE',
	'SERIEUSE', 'SERVANTE', 'SOLUTION', 'SURPRISE', 'TERMINAL', 'TONDEUSE',
	'TOURNANT', 'TRAGEDIE', 'TREMBLER', 'TRIBUNAL', 'TROPICAL', 'TROUPEAU',
	'VAILLANT', 'VEHICULE', 'VENDANGE', 'VIGILANT', 'VIRTUOSE', 'VRAIMENT'
];

export const WORDS: string[] = [...WORDS_5, ...WORDS_6, ...WORDS_7, ...WORDS_8];

export const VALID_GUESSES: Set<string> = new Set(WORDS.map((w) => w.toUpperCase()));

export function isValidWord(word: string): boolean {
	return VALID_GUESSES.has(word.toUpperCase());
}

export function getWordsByLength(length: number): string[] {
	return WORDS.filter((w) => w.length === length);
}
